#pragma once
#include "BatteryLevelEntry.h"
#include "PumpLevelEntry.h"
#include "PumpStateEntry.h"
#include "PingEntry.h"
#include "PongEntry.h"
#include "LoRaFeedbackEntry.h"
#include "LoRaConfigEntry.h"
#include "ConfigEntry.h"